### ISSUE TITLE
Does this not work on OTF?

### ISSUE THREAD

**Issue by drj11** [googlefonts/diffenator2#156]
I get a Python error: `KeyError: 'glyf'` when i try this on an OTF file.

```
diffenator2 diff -fb ChunkFive-Regular.otf -fa ChunkFive-Regular.otf -o diffout
[1/2] _diffenator "{'fonts_before': ['... 'new_font': 'ChunkFive-Regular.otf'}"
FAILED: diffout/Regular 
_diffenator "{'fonts_before': ['ChunkFive-Regular.otf'], 'fonts_after': ['ChunkFive-Regular.otf'], 'diffbrowsers': True, 'diffenator': True, 'out': 'diffout', 'imgs': False, 'styles': 'instances', 'characters': '.*', 'user_wordlist': None, 'filter_styles': 'Regular', 'font_size': 28, 'pt_size': 20, 'threshold': 0.9, 'precision': 28, 'no_words': False, 'no_tables': False, 'diffenator_template': '/Users/drj/font-venv/lib/python3.11/site-packages/diffenator2/templates/diffenator.html', 'command': 'diff', 'diffbrowsers_templates': [], 'debug_gifs': False, 'kwargs': {'no_diffenator': False}, 'no_diffenator': False, 'coords': 'wght=400', 'old_font': 'ChunkFive-Regular.otf', 'new_font': 'ChunkFive-Regular.otf'}"
Traceback (most recent call last):
  File "/Users/drj/font-venv/bin/_diffenator", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/drj/font-venv/lib/python3.11/site-packages/diffenator2/_diffenator.py", line 110, in main
    diff.diff_all()
  File "/Users/drj/font-venv/lib/python3.11/site-packages/diffenator2/_diffenator.py", line 38, in diff_all
    self.diff_tables()
  File "/Users/drj/font-venv/lib/python3.11/site-packages/diffenator2/_diffenator.py", line 45, in diff_tables
    self.tables = jfont.Diff(self.old_font.jFont, self.new_font.jFont)
                             ^^^^^^^^^^^^^^^^^^^
  File "/Users/drj/font-venv/lib/python3.11/site-packages/diffenator2/font.py", line 74, in jFont
    return jfont.TTJ(self.ttFont)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drj/font-venv/lib/python3.11/site-packages/diffenator2/jfont.py", line 197, in TTJ
    ttFont["glyf"].compile(ttFont)
    ~~~~~~^^^^^^^^
  File "/Users/drj/font-venv/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 455, in __getitem__
    table = self._readTable(tag)
            ^^^^^^^^^^^^^^^^^^^^
  File "/Users/drj/font-venv/lib/python3.11/site-packages/fontTools/ttLib/ttFont.py", line 462, in _readTable
    data = self.reader[tag]
           ~~~~~~~~~~~^^^^^
  File "/Users/drj/font-venv/lib/python3.11/site-packages/fontTools/ttLib/sfnt.py", line 108, in __getitem__
    entry = self.tables[Tag(tag)]
            ~~~~~~~~~~~^^^^^^^^^^
KeyError: 'glyf'
[2/2] _diffbrowsers "{'fonts_before': ...tor': False}, 'no_diffenator': False}"
ninja: build stopped: subcommand failed.
```

Does diffenator2 only work on TTFs? Which is fine, but it should be documented.

And if there are aspirations to have it work on OTFs as well, maybe that should be documented :)

(or is this just a simple bug?)

**Comment by m4rc1e** [comment]
> Does diffenator2 only work on TTFs? Which is fine, but it should be documented.

Correct. I'll add this to the README. Thank you for reporting. Honestly, it shouldn't be too difficult to add support for otfs so I'll raise this internally.
